import { DrinkProduct, Location } from "./types";

export const DRINK_IMAGES: Record<string, string> = {
  "monster-energy": "",
  "monster-ultra": "",
  "coca-cola": "",
  "sprite": "",
  "fanta-orange": "",
  "red-bull": "",
  "pepsi": "",
  "bembel-apfelwein": "",
  "fritz-kola": "",
  "club-mate": "",
};

export const DEFAULT_PRODUCTS: DrinkProduct[] = [
  {
    id: "monster-energy",
    name: "Monster Energy",
    brand: "Monster",
    category: "energy",
    imageUrl: DRINK_IMAGES["monster-energy"],
    volume: 500,
    description: "Green original energy drink",
  },
  {
    id: "monster-ultra",
    name: "Monster Ultra White",
    brand: "Monster",
    category: "energy",
    imageUrl: DRINK_IMAGES["monster-ultra"],
    volume: 500,
    description: "Zero sugar, zero calories energy",
  },
  {
    id: "coca-cola",
    name: "Coca-Cola",
    brand: "Coca-Cola",
    category: "soda",
    imageUrl: DRINK_IMAGES["coca-cola"],
    volume: 330,
    description: "The classic cola",
  },
  {
    id: "sprite",
    name: "Sprite",
    brand: "Coca-Cola",
    category: "soda",
    imageUrl: DRINK_IMAGES["sprite"],
    volume: 330,
    description: "Lemon-lime refreshment",
  },
  {
    id: "fanta-orange",
    name: "Fanta Orange",
    brand: "Coca-Cola",
    category: "soda",
    imageUrl: DRINK_IMAGES["fanta-orange"],
    volume: 330,
    description: "Orange flavored soda",
  },
  {
    id: "red-bull",
    name: "Red Bull",
    brand: "Red Bull",
    category: "energy",
    imageUrl: DRINK_IMAGES["red-bull"],
    volume: 250,
    description: "Gives you wings",
  },
  {
    id: "pepsi",
    name: "Pepsi",
    brand: "PepsiCo",
    category: "soda",
    imageUrl: DRINK_IMAGES["pepsi"],
    volume: 330,
    description: "The bold cola",
  },
  {
    id: "bembel-apfelwein",
    name: "Bembel Apfelwein",
    brand: "Bembel With Care",
    category: "cider",
    imageUrl: DRINK_IMAGES["bembel-apfelwein"],
    volume: 500,
    description: "Traditional Frankfurt apple wine",
  },
  {
    id: "fritz-kola",
    name: "fritz-kola",
    brand: "fritz-kulturgüter",
    category: "soda",
    imageUrl: DRINK_IMAGES["fritz-kola"],
    volume: 330,
    description: "Extra caffeinated cola from Hamburg",
  },
  {
    id: "club-mate",
    name: "Club-Mate",
    brand: "Loscher",
    category: "other",
    imageUrl: DRINK_IMAGES["club-mate"],
    volume: 500,
    description: "Mate-based caffeinated drink",
  },
];

export const DEFAULT_LOCATIONS: Location[] = [
  {
    id: "loc-fridge",
    name: "Fridge",
    address: "Cold · 4°C",
    color: "#3b82f6",
    icon: "Refrigerator",
  },
  {
    id: "loc-freezer",
    name: "Freezer",
    address: "Frozen · -18°C",
    color: "#06b6d4",
    icon: "Snowflake",
  },
  {
    id: "loc-shelf",
    name: "Shelf",
    address: "Room temp · Kitchen",
    color: "#eab308",
    icon: "Archive",
  },
  {
    id: "loc-backpack",
    name: "Backpack",
    address: "On the go",
    color: "#22c55e",
    icon: "Backpack",
  },
  {
    id: "loc-desk",
    name: "Desk",
    address: "Room temp · Office",
    color: "#a855f7",
    icon: "Monitor",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  energy: "Energy",
  soda: "Soda",
  juice: "Juice",
  water: "Water",
  beer: "Beer",
  cider: "Cider",
  other: "Other",
};

export const CATEGORY_COLORS: Record<string, string> = {
  energy: "#22c55e",
  soda: "#3b82f6",
  juice: "#f97316",
  water: "#06b6d4",
  beer: "#eab308",
  cider: "#ef4444",
  other: "#a855f7",
};
